name: Github CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - name: Install dependecies
        run: |
          pnpm i
      - name: Run build process
        run: |
          pnpm build

#      - name: Publish
#        run: |
#            npm publish
#        env:
#          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
